---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
        - "recipe[apt]"
        - "recipe[wiw-mysql]"
    attributes:
      wiw_mysql:
        password_vault: 'mysql' 
        tablename: 'wiw' 
        username: 'wiw' 
      chef-vault:
        databag_fallback: true
