source 'https://rubygems.org'

gem 'chef-vault'

group :lint do
  gem 'foodcritic', '~> 6.0.1'
  gem 'rubocop', '~> 0.37.2'
end

group :spec do
  gem 'rspec', '~> 3.4.0'
  gem 'chefspec', '~> 4.5.0'
end

group :integration do
  gem 'test-kitchen', '~> 1.5.0'
  gem 'kitchen-vagrant', '~> 0.19.0'
end

group :dev do
  gem 'rake', '~> 10.5.0'
  gem 'berkshelf', '~> 4.2.3'
end
