name             'wiw-mysql'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures wiw-mysql'
long_description 'Installs/Configures wiw-mysql'
version          '0.1.0'
issues_url       'https://github.com/wiw-boldfield/ops-exercise/issues'
source_url       'https://github.com/wiw-boldfield/ops-exercise'

depends 'mysql'
depends 'chef-vault'
depends 'mysql2_chef_gem'
depends 'database'
