---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7.2

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    driver:
      network:
        -  ["forwarded_port", {guest: 80, host: 8080}]
        -  ["forwarded_port", {guest: 443, host: 4430}]
    run_list:
        - "recipe[apt]"
        - "recipe[wiw-standalone-blog-rolebook]"
    attributes:
      chef-vault:
        databag_fallback: true
