source 'https://rubygems.org'

group :integration do
  gem 'test-kitchen', '~> 1.5.0'
  gem 'kitchen-vagrant', '~> 0.19.0'
end

group :dev do
  gem 'rake', '~> 10.5.0'
  gem 'berkshelf', '~> 4.2.3'
end

