name             'wiw-hhvm'
maintainer       'Brian Oldfield'
maintainer_email 'brian+wiw@oldfield.io'
license          'All rights reserved'
description      'Installs/Configures wiw-hhvm'
long_description 'Installs/Configures wiw-hhvm'
version          '0.1.0'
issues_url       'https://github.com/wiw-boldfield/ops-exercise/issues'
source_url       'https://github.com/wiw-boldfield/ops-exercise'

depends 'hhvm'
depends 'logrotate'
