name             'wiw-nginx'
maintainer       'Brian Oldfield'
maintainer_email 'brian+wiw@oldfield.io'
license          'All rights reserved'
description      'Wrapper around community nginx cookbook'
long_description 'Wrapper around community nginx cookbook'
version          '0.1.0'
issues_url       'https://github.com/wiw-boldfield/ops-exercise/issues'
source_url       'https://github.com/wiw-boldfield/ops-exercise'

depends 'nginx'
depends 'logrotate'
