require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'foodcritic'
require 'kitchen'

namespace :style do
  desc 'Run Ruby style checks'
  RuboCop::RakeTask.new(:ruby)

  desc 'Run Chef style checks'
  FoodCritic::Rake::LintTask.new(:chef) do |t|
    t.options = {
      fail_tags: ['any'],
      tags: [
        '~FC005',
        '~FC015',
        '~FC023'
      ]
    }
  end
end

desc 'Run style checks'
task style: ['style:ruby', 'style:chef']

desc 'run ChefSpec'
RSpec::Core::RakeTask.new(:spec)
